baseurl:
title: Matthew Siu
subtitle: Home
author: Matthew Siu
simple_search: http://google.com/search
description: Matthew Siu
name: tufte
permalink: /:title/

# markdown: kramdown
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"
timezone: America/New_York
excerpt_separator: <!--more--> # you can specify your own separator, of course.
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "UploadToGithub.Rakefile",
    "README.md",
  ]
embed_tweets: true
# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# theme: tufte-pandoc-jekyll

# gems:
#   - jekyll-pandoc

# markdown: Pandoc
# pandoc:
#   extensions:
#     - section-divs
#     - from: "markdown+tex_math_single_backslash"
#     - filter: "pandoc-sidenote"

collections:
  notes:
    output: true
    permalink: /:title
  impressions:
    output: true
    permalink: /:title

post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/
